// <auto-generated />
using System;
using DeepLearningServer.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeepLearningServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeepLearningServer.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrainingRecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingRecordId");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("DeepLearningServer.Models.LogRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LevelString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogRecords", (string)null);
                });

            modelBuilder.Entity("DeepLearningServer.Models.ProgressEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BestIteration")
                        .HasColumnType("float");

                    b.Property<bool>("IsTraining")
                        .HasColumnType("bit");

                    b.Property<string>("LearningRateParameters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainingRecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingRecordId");

                    b.ToTable("ProgressEntries");
                });

            modelBuilder.Entity("DeepLearningServer.Models.TrainingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Accuracy")
                        .HasColumnType("float");

                    b.Property<int>("BatchSize")
                        .HasColumnType("int");

                    b.Property<int>("BestIteration")
                        .HasColumnType("int");

                    b.Property<int>("ClassifierCapacity")
                        .HasColumnType("int");

                    b.Property<bool>("ComputeHeatMap")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EnableHistogramEqualization")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HorizontalFlip")
                        .HasColumnType("bit");

                    b.Property<float>("HueOffset")
                        .HasColumnType("real");

                    b.Property<int>("ImageCacheSize")
                        .HasColumnType("int");

                    b.Property<int>("ImageChannels")
                        .HasColumnType("int");

                    b.Property<int>("ImageHeight")
                        .HasColumnType("int");

                    b.Property<int>("ImageSize")
                        .HasColumnType("int");

                    b.Property<int>("ImageWidth")
                        .HasColumnType("int");

                    b.Property<double>("Loss")
                        .HasColumnType("float");

                    b.Property<float>("MaxBrightnessOffset")
                        .HasColumnType("real");

                    b.Property<float>("MaxContrastGain")
                        .HasColumnType("real");

                    b.Property<float>("MaxGamma")
                        .HasColumnType("real");

                    b.Property<float>("MaxGaussianDeviation")
                        .HasColumnType("real");

                    b.Property<float>("MaxHorizontalShear")
                        .HasColumnType("real");

                    b.Property<float>("MaxHorizontalShift")
                        .HasColumnType("real");

                    b.Property<float>("MaxRotation")
                        .HasColumnType("real");

                    b.Property<float>("MaxSaltPepperNoise")
                        .HasColumnType("real");

                    b.Property<float>("MaxSaturationGain")
                        .HasColumnType("real");

                    b.Property<float>("MaxScale")
                        .HasColumnType("real");

                    b.Property<float>("MaxSpeckleDeviation")
                        .HasColumnType("real");

                    b.Property<float>("MaxVerticalShear")
                        .HasColumnType("real");

                    b.Property<float>("MaxVerticalShift")
                        .HasColumnType("real");

                    b.Property<float>("MinContrastGain")
                        .HasColumnType("real");

                    b.Property<float>("MinGamma")
                        .HasColumnType("real");

                    b.Property<float>("MinGaussianDeviation")
                        .HasColumnType("real");

                    b.Property<float>("MinSaltPepperNoise")
                        .HasColumnType("real");

                    b.Property<float>("MinSaturationGain")
                        .HasColumnType("real");

                    b.Property<float>("MinScale")
                        .HasColumnType("real");

                    b.Property<float>("MinSpeckleDeviation")
                        .HasColumnType("real");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Progress")
                        .HasColumnType("real");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SettingID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("UsePretrainedModel")
                        .HasColumnType("bit");

                    b.Property<bool>("VerticalFlip")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TrainingRecords", (string)null);
                });

            modelBuilder.Entity("DeepLearningServer.Models.Category", b =>
                {
                    b.HasOne("DeepLearningServer.Models.TrainingRecord", "TrainingRecord")
                        .WithMany("Categories")
                        .HasForeignKey("TrainingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingRecord");
                });

            modelBuilder.Entity("DeepLearningServer.Models.ProgressEntry", b =>
                {
                    b.HasOne("DeepLearningServer.Models.TrainingRecord", "TrainingRecord")
                        .WithMany("ProgressHistory")
                        .HasForeignKey("TrainingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingRecord");
                });

            modelBuilder.Entity("DeepLearningServer.Models.TrainingRecord", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("ProgressHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
